name: Build and Publish

on:
  # run it on push to the default repository branch
  push:


  # run it during pull request
 

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:

    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Working Directory
        shell: bash
        run: pwd
      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to Github Packages
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        run: docker image build -t vladimir:v1

      - name: Tagging 
        run: docker tag vladimir:v1 ${{ secrets.DOCKER_HUB_USERNAME }}/mr123

      - name: pomoziboze
        run: docker push vladimir1234/mr123:v1

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
