name: Docker Image CI

on:
  push:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Working Directory
      shell: bash
      run: pwd

   # - name: Set up Docker Buildx
    #  id: buildx
     # uses: docker/setup-buildx-action@v1*/

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        env:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


    - name: Build the Docker image and push to DockerHub
     # uses: docker/build-push-action@v2
      run: docker image build -t proba:latest

    - name: Tagovanje
      run: docker tag proba:latest ${{secrets.DOCKER_HUB_USERNAME}}/mr123:proba
    - name: Docker Push
      run: docker push vladimir1234/mr123:proba
